version: '3.8'
services:
  page:
    image: node:latest
    build: .
    container_name: dom-glass
    working_dir: /app
    volumes:
      - ./:/app
    env_file: 
      - .env
    ports:
      - ${PORT}:${PORT}